# Generated by Django 2.1.2 on 2018-11-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('publ_date', models.DateField()),
                ('body', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
